name: Deploy to Snowflake

on:
  push:
    branches:
      - dev
      - qa
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and Install SnowSQL
        run: |
          curl -o snowsql-latest-linux_x86_64.bash https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/latest/snowsql-linux_x86_64.bash
          chmod +x snowsql-latest-linux_x86_64.bash
          sudo ./snowsql-latest-linux_x86_64.bash

      - name: Run Snowflake Deployment
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: PUBLIC
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        run: |
          ~/bin/snowsql -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -p $SNOWFLAKE_PASSWORD \
                        -d $SNOWFLAKE_DATABASE -s $SNOWFLAKE_SCHEMA -r $SNOWFLAKE_ROLE \
                        -w $SNOWFLAKE_WAREHOUSE -f snowflake/${{ github.ref_name }}/deploy.sql
